### ISSUE TITLE
A11y issues with welcome page

### ISSUE THREAD

**Issue by MelSumner** [ember-cli/ember-welcome-page#119]
There are several accessibility issues identified on the page generated by this addon. 

- [ ] color contrast - either the color contrast should be increased, or the font sizes should be increased. 
- [ ] page must have at least one main landmark
- [x] page must contain a level-one heading
- [ ] all page content must be contained my landmark regions - for these purposes, `<main>` would suffice.

**Comment by jenweber** [comment]
Here's a screenshot showing some of the areas that need attention:

![Screen Shot 2019-04-19 at 6 01 10 PM](https://user-images.githubusercontent.com/16627268/56445831-38118200-62cd-11e9-9655-3fb57d17ab86.png)

**Comment by jenweber** [comment]
Color contrast updates should follow the branding guidelines https://emberjs.com/images/brand/Ember-Brand-Guidelines.pdf They use a darker shade of red that might resolve some of these problems

**Comment by ijlee2** [comment]
Will close this issue as we now check that the `<WelcomePage>` component passes `a11yAudit()` from `ember-a11y-testing`.

https://github.com/ember-cli/ember-welcome-page/blob/v7.0.0/test-app/tests/integration/components/welcome-page-test.js#L25-L27
