### ISSUE TITLE
likely more people need commit/release privs

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-welcome-page#17]
As this ships with ember-cli, it should likely have atleast rob and myself also \w commit + release privs.

We could also consider moving it to ember-cli org...

**Comment by rwjblue** [comment]
Ya, I think the plan was to move to ember-cli org once included by default.  I discussed with @acorncom and @locks and I believe they are :+1:

**Comment by locks** [comment]
@rwjblue already has release privs. I'll transfer the repo to ember-cli.

**Comment by stefanpenner** [comment]
@locks now you are, don't break anything ;)

**Comment by locks** [comment]
:shipit:
