### ISSUE TITLE
Strange cache fixation

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-welcome-page#19]
Haven't been able to narrow this down much but, it appears that it is possible to _sometimes_ cause `GET /` to mix last-modified-at up, sometimes providing the last-modified of welcome.html for the apps index.html. This results in a stale `/` being served, often an unrelated app apps (maybe one that ran previously) to be provided.

Using Chrome Version 51.0.2698.0 canary (64-bit)

Not entirely sure its this add-on, but removing it appears to immediately mitigate the issue...

**Comment by stefanpenner** [comment]
It seems that:

1. `ember new`
2. navigate to `/`, get welcome screen
3. `ember g application`
4. navigate to `/`, get blank screen
5. `cd app; git clean -fdx`
6. navigate to '/'` get blank screen <-- fixation
7. curl `/` get welcome screen

**Comment by stefanpenner** [comment]
also seems to happen in `Chrome Version 49.0.2623.110 (64-bit)`, but not in safari...

**Comment by rwjblue** [comment]
I removed usage of `res.sendFile` (in favor of `res.send`) in #20.  The options we were passing in to `sendFile` may have accounted for the extra cache headers you were seeing.

**Comment by locks** [comment]
I've merged #20, can you confirm this is fixed @stefanpenner?

**Comment by rwjblue** [comment]
@stefanpenner - I released v1.0.1 to make it easier to test/confirm.

**Comment by stefanpenner** [comment]
@rwjblue looks like your fixes addressed the issue
