### ISSUE TITLE
Newly generated ember-cli app throws 404 when running acceptance test 'visiting /'

### ISSUE THREAD

**Issue by Gaurav0** [ember-cli/ember-welcome-page#204]
Steps to reproduce:

1. Generate a new ember app with ember-cli 3.13.1
2. Add (or generate) the following application acceptance test:

```
import { module, test } from 'qunit';
import { visit, currentURL } from '@ember/test-helpers';
import { setupApplicationTest } from 'ember-qunit';

module('Acceptance | application', function(hooks) {
  setupApplicationTest(hooks);

  test('visiting /', async function(assert) {
    await visit('/');

    assert.equal(currentURL(), '/');
  });
});
```

3. Run ember-test --server
4. Look in console in dev tools

construction.png:1 GET http://localhost:7357/50490650938934/tests/ember-welcome-page/images/construction.png 404 (Not Found)

**Comment by ijlee2** [comment]
Closing this issue as (I'm suspecting that) it is no longer relevant.
