### ISSUE TITLE
ember-inspector: "Ember application not detected"

### ISSUE THREAD

**Issue by ro0gr** [ember-cli/ember-welcome-page#22]
ember-welcome-page: 1.0.1
ember-cli: 2.4.3
ember: 2.5.0
ember-inspector: 1.9.4

Ember inspector is unable to recognize ember app in a #fresh ember app with `ember-welcome-page`:

![ember-not-detected](https://cloud.githubusercontent.com/assets/875361/14576661/131056ae-0374-11e6-89c7-b0a92a138d5f.png)

**Comment by rwjblue** [comment]
Well.  Technically, it isn't an Ember App (it is just static HTML/CSS/images/etc).

**Comment by rwjblue** [comment]
Seems like we should have some sort of awareness by ember-inspector so it shows a slightly different message (perhaps even a complimenting welcoming message)...

**Comment by ro0gr** [comment]
Yes, I see. It may be confusing for newcomers to see such a message with their freshly new apps.

**Comment by ro0gr** [comment]
Should I create an issue in the `ember-inspector` repo?

**Comment by rwjblue** [comment]
No, this is fine for now.

@acorncom / @locks - Thoughts?

**Comment by acorncom** [comment]
Nice catch @ro0gr @rwjblue none at the moment, I'll think about it some.  My understanding is Ember Inspector does some fancy shenanigans to check things and we don't even have JS running on that page.  We might be able to setup some sort of data attribute on the page that the inspector looks for so it can display a notice ...

**Comment by acorncom** [comment]
Yes, a complimenting message would be good. I'll open an issue over at the inspector repo to discuss it there (before just sending in a PR :smile:)
