### ISSUE TITLE
Isn't disabled inside of addons

### ISSUE THREAD

**Issue by ebryn** [ember-cli/ember-welcome-page#25]
```
ember addon my-addon
ember g route application --dummy
```

Welcome page is still displayed.

Workaround: remove the ember-welcome-page addon from the addon's package.json

**Comment by rwjblue** [comment]
https://github.com/ember-cli/ember-welcome-page/blob/master/index.js#L66-L103 needs to be updated to search `app` when in an app but both `app` and `tests/dummy/app` when in an addon.

**Comment by vvscode** [comment]
@locks  @ebryn  it's not actual ? ( I'm about version )

And if possible - can you how this issues should be tested ( I mean unit tests ) - just a idea, cause I didn't mind

**Comment by locks** [comment]
Hey @vvscode, your help is appreciated, but since this is specific to the 1.x versions of the addon and this much time as passed already, I think I'm closing the issues. Reach us in the #-team-learning channel, because there's a couple other things you can help us with!
