### ISSUE TITLE
This project appears to introduce 2288 files via itself and its deps

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-welcome-page#33]
- [x] lodash 1023 https://github.com/ember-cli/ember-welcome-page/pull/36

Rather then using all of lodash, it appears we merely require `lodash.template` module.

----

Other deps, that we will most likely fixup independently of this issue, but help would be nice

- [x] broccoli-funnel 571 https://github.com/broccolijs/broccoli-funnel/pull/74
- [x] broccoli-merge-trees 553 https://github.com/broccolijs/broccoli-merge-trees/pull/48
- [x] ember-cli-version-checker 51 https://github.com/rwjblue/ember-cli-version-checker/pull/18
- [x] exists-sync 8 https://github.com/ember-cli/exists-sync/pull/3
- [x] walk-sync 48 https://github.com/joliss/node-walk-sync/pull/28

**Comment by rtablada** [comment]
![clapping](http://i.imgur.com/ULXUQQd.gif)
