### ISSUE TITLE
Import only lodash-template instead of the whole lodash

### ISSUE THREAD

**Issue by locks** [ember-cli/ember-welcome-page#34]
As mentioend in https://github.com/ember-cli/ember-welcome-page/issues/33, we are currently unnecessarily adding over 1000 files by importing the whole of lodash. We should fix this! :)

Steps:
- Replace https://github.com/ember-cli/ember-welcome-page/blob/master/package.json#L55 with https://www.npmjs.com/package/lodash.template
- In https://github.com/ember-cli/ember-welcome-page/blob/f41b11ee2a7c43090cdcace3afd176738af61a1e/index.js#L11 import `lodash.template` instead
- Test locally to make sure addon is still working

**Comment by Turbo87** [comment]
resolved by #36
