### ISSUE TITLE
Convert to TS or supply ambient type definitions

### ISSUE THREAD

**Issue by chriskrycho** [ember-cli/ember-welcome-page#387]
As part of [Ember.js RFC #0800](https://rfcs.emberjs.com/id/0800-ts-adoption-plan), this package needs to supply type definitions. Preferably, this would happen by converting to TS and generating from the source; as an alternative, it can publish ambient types (presumably starting with the ones on DefinitelyTyped).

All the members of the Typed Ember team are happy to advise on how to do this; feel free to reach out [in #dev-typescript on Discord][discord] if you have questions!

[discord]: https://discord.com/channels/480462759797063690/786312479620726804

**Comment by ijlee2** [comment]
@chriskrycho and @ember-cli/ember-cli

I've completed the task. Can you review the project as a whole? Between now and Dec 22nd (I'm in CET), I can be available to clarify questions, fix bugs, and troubleshoot with releasing a new major version.
