### ISSUE TITLE
Style bleeds out from ember-welcome-page.css

### ISSUE THREAD

**Issue by nathanhammond** [ember-cli/ember-welcome-page#63]
We should scope all of these styles or revise the build setup in the 1.X branch of `ember-welcome-page`:

https://github.com/ember-cli/ember-cli/issues/6389

/cc @ballPointPenguin

**Comment by acorncom** [comment]
@ballPointPenguin Would love to hear more details about the issue you hit here, could you send over your `package.json` file re: `ember-welcome-page`?  We released a new 2.x series in the last week, but were specifically aiming for it to not affect folks with the 1.x line in their apps ...

/cc @locks

**Comment by ballPointPenguin** [comment]
This demonstrates the issue exactly: https://github.com/ballPointPenguin/ember-welcome-style

As I was testing this I determined that it only occurs with ember-welcome-page v2.0.0 and v2.0.1

**Comment by locks** [comment]
v2.0.2 with https://github.com/ember-cli/ember-welcome-page/pull/65 is out
