### ISSUE TITLE
Documentation links are broken for newer than stable releases

### ISSUE THREAD

**Issue by locks** [ember-cli/ember-welcome-page#72]
Text below from @chrisself from https://github.com/ember-cli/ember-cli/issues/6869

<hr>

Hey all,

I'm seeing that ember-cli installs versions `2.13.0-beta.1` of ember-data and ember-source. When creating a new project, ember-welcome-page parses the version number and provides links to the Quick Start introduction and Guides and Tutorials page. However, I don't believe 2.13.0 has online documentation yet, so both links result in a 404 error.

Here are the two URLs I received:

https://guides.emberjs.com/v2.13.0/getting-started/quick-start/
https://guides.emberjs.com/v2.13.0/tutorial/ember-cli/

Because ember-welcome-page is parsing the correct version of Ember, I'm not sure where this issue belongs exactly. As a note, this is my first time opening an issue here, so please let me know if more information is needed.

---

Output from `ember version --verbose && npm --version`:
```
ember-cli: 2.12.0
http_parser: 2.7.0
node: 7.4.0
v8: 5.4.500.45
uv: 1.10.1
zlib: 1.2.8
ares: 1.10.1-DEV
modules: 51
openssl: 1.0.2j
icu: 58.2
unicode: 9.0
cldr: 30.0.3
tz: 2016j
os: darwin x64
4.0.5
```

**Comment by locks** [comment]
My suggestion would be to decrease the minor version if the user is using a beta. I think this is the safest way to go, as newer-than-beta releases might include breaking changes, and we'd have to do some sort of network request to make sure.

cc @rwjblue

**Comment by acorncom** [comment]
I'd be inclined to drop to `/current` if we're on an alpha, beta or master

**Comment by locks** [comment]
What if for some reason you're on an older non-release channel?

**Comment by acorncom** [comment]
How many folks on non-release channels are ever going to see the welcome page?  I'd guess that most folks stepping off the default beaten path like that aren't going to be looking to the welcome page / guides for help ... 😀

**Comment by locks** [comment]
Well, someone did 👼

**Comment by locks** [comment]
Can you PR?

**Comment by rwjblue** [comment]
I agree with:

> I'd be inclined to drop to /current if we're on an alpha, beta or master

We should link to `/current` for any non-tagged versions...

**Comment by acorncom** [comment]
A good PR to resolve this issue would add a few tests to ensure that the `emberVersion` computed property in the welcome-page component (https://github.com/ember-cli/ember-welcome-page/blob/master/addon/components/welcome-page.js#L7-L11) works as intended.
