### ISSUE TITLE
Background colour

### ISSUE THREAD

**Issue by twokul** [ember-cli/ember-welcome-page#76]
![screen shot 2017-06-25 at 12 46 21 pm](https://user-images.githubusercontent.com/1131196/27519255-7f73c948-59a4-11e7-9427-d8ca3cfc2678.png)

the whole page should have background colour set not just the container

**Comment by acorncom** [comment]
Although this doesn't look as snazzy as it could on a full screen, this is actually done deliberately to keep the component's CSS from bleeding into the containing app in anyway. Without it, we begin to alter CSS when that may not be appreciated by folks who left it in their blueprint. If you check the original history here, you'll see that your suggestion is the way I started this and it wasn't liked ... :grinning:

Will close for now, but please speak up if I'm missing something.

**Comment by trentmwillis** [comment]
Just a thought, we could set the component's height to `100vh` which would give it full viewport coverage for most browsers.

**Comment by twokul** [comment]
@acorncom submitted a fix, basically what @trentmwillis said

**Comment by acorncom** [comment]
@twokul :thumbsup: thx!
