### ISSUE TITLE
Consider adding in loading / error.hbs files for apps by default

### ISSUE THREAD

**Issue by acorncom** [ember-cli/ember-welcome-page#8]
More info on this mentioned here: https://github.com/ember-cli/ember-cli/issues/4570

**Comment by stefanpenner** [comment]
i don't think/know if that is directly related to welcome-page or not.

**Comment by rwjblue** [comment]
Ya, seems unrelated to our purpose here...

**Comment by stefanpenner** [comment]
We should totally do this, but i suspect is isn't related to this addon.

**Comment by acorncom** [comment]
:+1: Let me know if you want me to help with this somewhere else

**Comment by stefanpenner** [comment]
@acorncom we totally would, likely its own add-on.
